"""empty message

Revision ID: 4e622faed37d
Revises: None
Create Date: 2015-07-10 15:11:48.368402

"""

# revision identifiers, used by Alembic.
revision = '4e622faed37d'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registers')
    ### end Alembic commands ###
